name: Lint Commit Messages

on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: npm install --no-save
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run:
          npx commitlint --from="origin/${{ github.base_ref }}" --to="origin/${{ github.head_ref }}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
