name: Validate Code

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 11.x, 12.x]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.ey.npme.io

      - name: install dependencies
        run: npm install --no-save
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: lint js
        run: npm run lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: run tests
        run: npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
